### ISSUE TITLE
Migrate WordPress Users into contentful

### ISSUE THREAD

**Issue by Sachinlo** [jonashcroft/wp-to-contentful#2]
Hi,

Hope you are doing well.
Actually, I have one query regarding to the migration that do you have any idea about how to migrate the wordpress users into contentful.

Thanks,
Sachin

**Comment by jonashcroft** [comment]
Hey,

It really depends on your Content Model in Contentful. Contentful can't be used to house registered users/visitors like WordPress does - so you'd have to handle these in an external database somewhere.

In terms of transferring administrators/editors, if these users have created posts in WordPress, then it would be a case of manually creating accounts for these editors in Contentful, migrating their blog posts and assigning the posts to the users (either manually or using a script similar to this).

**Comment by Sachinlo** [comment]
Hey,

Thank you for the response do you know how to do that with this script i mean where i need to change the code do you have any sample code for it that how to use in this script.
